--------------------------------------------------------
--  Fichier créé - lundi-mai-01-2023   
--------------------------------------------------------
DROP TABLE "JYHED"."EMPLOYE";
DROP TABLE "JYHED"."EMPLOYEE";
DROP TABLE "JYHED"."EMPRUNTS";
DROP TABLE "JYHED"."ENFANT";
DROP TABLE "JYHED"."FOURNIR";
DROP TABLE "JYHED"."HISTORY";
DROP TABLE "JYHED"."PARTENAIRE";
DROP TABLE "JYHED"."STOCK";
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "JYHED"."EMPLOYE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"CIN" NUMBER, 
	"DESIGNATION" VARCHAR2(50 BYTE), 
	"ADRESSE" VARCHAR2(50 BYTE), 
	"MDP" VARCHAR2(20 BYTE), 
	"NUM" NUMBER, 
	"GENDER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "JYHED"."EMPLOYEE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"CIN" NUMBER, 
	"SEXE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPRUNTS
--------------------------------------------------------

  CREATE TABLE "JYHED"."EMPRUNTS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"RFID" VARCHAR2(20 BYTE), 
	"DATE_ENTREE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENFANT
--------------------------------------------------------

  CREATE TABLE "JYHED"."ENFANT" 
   (	"ID" VARCHAR2(8 BYTE), 
	"NOM" VARCHAR2(10 BYTE), 
	"PRENOM" VARCHAR2(10 BYTE), 
	"AGE" NUMBER(10,0), 
	"DATE_DE_NAISSANCE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNIR
--------------------------------------------------------

  CREATE TABLE "JYHED"."FOURNIR" 
   (	"IDS" NUMBER, 
	"IDP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HISTORY
--------------------------------------------------------

  CREATE TABLE "JYHED"."HISTORY" 
   (	"DATE_HISTORIQUE" DATE, 
	"NOMP" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTENAIRE
--------------------------------------------------------

  CREATE TABLE "JYHED"."PARTENAIRE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"NUMTEL" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"QUANTITE" NUMBER, 
	"SOMME" VARCHAR2(20 BYTE), 
	"DATE_CONVENTION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCK
--------------------------------------------------------

  CREATE TABLE "JYHED"."STOCK" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"QUANTITE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DATES" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JYHED.EMPLOYE
SET DEFINE OFF;
Insert into JYHED.EMPLOYE (ID,NOM,PRENOM,CIN,DESIGNATION,ADRESSE,MDP,NUM,GENDER) values ('11','JJ','HHJ','1111111','Gestion_partenaire','a@gmail.com','OO345678','2134567','Homme');
Insert into JYHED.EMPLOYE (ID,NOM,PRENOM,CIN,DESIGNATION,ADRESSE,MDP,NUM,GENDER) values ('15443','JYHED','HORCHANI','12233455','Admin','jihed.horchani@gmail.com','L{jgf72933328','50711106','Homme');
Insert into JYHED.EMPLOYE (ID,NOM,PRENOM,CIN,DESIGNATION,ADRESSE,MDP,NUM,GENDER) values ('76543','yousef','grissa','123456','Gestion_enfant','test@gmail.com','Jqtejcpk345','40506070','Homme');
REM INSERTING into JYHED.EMPLOYEE
SET DEFINE OFF;
Insert into JYHED.EMPLOYEE (ID,NOM,CIN,SEXE) values ('1','Saif','4','Homme');
Insert into JYHED.EMPLOYEE (ID,NOM,CIN,SEXE) values ('2','Emna','77777','Femme');
Insert into JYHED.EMPLOYEE (ID,NOM,CIN,SEXE) values ('4','Kamel','145','Homme');
Insert into JYHED.EMPLOYEE (ID,NOM,CIN,SEXE) values ('6','Amir','4444','Homme');
Insert into JYHED.EMPLOYEE (ID,NOM,CIN,SEXE) values ('3','Yassine','587','Homme');
Insert into JYHED.EMPLOYEE (ID,NOM,CIN,SEXE) values ('5','Wcv','777','Femme');
REM INSERTING into JYHED.EMPRUNTS
SET DEFINE OFF;
REM INSERTING into JYHED.ENFANT
SET DEFINE OFF;
Insert into JYHED.ENFANT (ID,NOM,PRENOM,AGE,DATE_DE_NAISSANCE) values ('54321','arij','horchani','12',to_date('01/01/00','DD/MM/RR'));
Insert into JYHED.ENFANT (ID,NOM,PRENOM,AGE,DATE_DE_NAISSANCE) values ('0','JYHED','HORCHANI','20',to_date('04/01/00','DD/MM/RR'));
REM INSERTING into JYHED.FOURNIR
SET DEFINE OFF;
REM INSERTING into JYHED.HISTORY
SET DEFINE OFF;
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('15/03/23','DD/MM/RR'),'azrrt','147','suppression');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('15/03/23','DD/MM/RR'),'yassine','145','suppression');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('24/04/23','DD/MM/RR'),'YASS','58','modification');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('27/04/23','DD/MM/RR'),'YASS','40','ajout');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('27/04/23','DD/MM/RR'),'zara','111','ajout');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('27/04/23','DD/MM/RR'),'aefgv','8','ajout');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('27/04/23','DD/MM/RR'),'zara','12','ajout');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('27/04/23','DD/MM/RR'),'YASS','17','ajout');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('27/04/23','DD/MM/RR'),'YASS','77','ajout');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('27/04/23','DD/MM/RR'),'aggg','87','suppression');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('27/04/23','DD/MM/RR'),'aggg','87','ajout');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('27/04/23','DD/MM/RR'),'YASS','58','suppression');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('27/04/23','DD/MM/RR'),'YASS','58','ajout');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('27/04/23','DD/MM/RR'),'aefgv','8','suppression');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('27/04/23','DD/MM/RR'),'aefgv','8','ajout');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('27/04/23','DD/MM/RR'),'aefgv','8','suppression');
Insert into JYHED.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('27/04/23','DD/MM/RR'),'aefgv','8','ajout');
REM INSERTING into JYHED.PARTENAIRE
SET DEFINE OFF;
Insert into JYHED.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('14','zara','+21697404777',null,'0','40',to_date('01/01/00','DD/MM/RR'));
Insert into JYHED.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('4','aefgv','+21697404777','jouet','4',null,to_date('01/01/00','DD/MM/RR'));
Insert into JYHED.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('6','aefgv','+21697404777','vet','4',null,to_date('01/01/00','DD/MM/RR'));
Insert into JYHED.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('58','YASS','+21697404777',null,'0','60',to_date('01/01/00','DD/MM/RR'));
Insert into JYHED.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('40','YASS','+21697404777',null,'0','60',to_date('01/01/00','DD/MM/RR'));
Insert into JYHED.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('111','zara','+21697404777',null,'0','40',to_date('01/01/00','DD/MM/RR'));
Insert into JYHED.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('8','aefgv','+21697404777','vet','4',null,to_date('01/01/00','DD/MM/RR'));
Insert into JYHED.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('12','zara','+21697404777',null,'0','40',to_date('01/01/00','DD/MM/RR'));
Insert into JYHED.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('17','YASS','+21697404777',null,'0','60',to_date('01/01/00','DD/MM/RR'));
Insert into JYHED.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('77','YASS','+21697404777',null,'0','60',to_date('01/01/00','DD/MM/RR'));
Insert into JYHED.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('87','aggg','+21697404777','alimentation','4',null,to_date('01/01/00','DD/MM/RR'));
REM INSERTING into JYHED.STOCK
SET DEFINE OFF;
Insert into JYHED.STOCK (ID,NOM,QUANTITE,TYPE,DATES) values ('2','jyhed','50','tye',to_date('03/01/00','DD/MM/RR'));
Insert into JYHED.STOCK (ID,NOM,QUANTITE,TYPE,DATES) values ('55','yass','70','zettt',to_date('01/01/01','DD/MM/RR'));
Insert into JYHED.STOCK (ID,NOM,QUANTITE,TYPE,DATES) values ('30','y','50','5j',to_date('01/01/00','DD/MM/RR'));
Insert into JYHED.STOCK (ID,NOM,QUANTITE,TYPE,DATES) values ('20','jeuuheuud','50','fruit',to_date('01/01/00','DD/MM/RR'));
Insert into JYHED.STOCK (ID,NOM,QUANTITE,TYPE,DATES) values ('44','yass','70','zettt',to_date('01/01/01','DD/MM/RR'));
Insert into JYHED.STOCK (ID,NOM,QUANTITE,TYPE,DATES) values ('66','yass','70','zettt',to_date('01/01/01','DD/MM/RR'));
Insert into JYHED.STOCK (ID,NOM,QUANTITE,TYPE,DATES) values ('77','yass','70','zettt',to_date('01/01/01','DD/MM/RR'));
Insert into JYHED.STOCK (ID,NOM,QUANTITE,TYPE,DATES) values ('76','jeuuheuud','50','fruit',to_date('01/01/00','DD/MM/RR'));
Insert into JYHED.STOCK (ID,NOM,QUANTITE,TYPE,DATES) values ('1234','jyhed','1000','tye',to_date('03/01/00','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JYHED"."EMPLOYEE_PK" ON "JYHED"."EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNIR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JYHED"."FOURNIR_PK" ON "JYHED"."FOURNIR" ("IDS", "IDP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARTENAIRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JYHED"."PARTENAIRE_PK" ON "JYHED"."PARTENAIRE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STOCK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JYHED"."STOCK_PK" ON "JYHED"."STOCK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "JYHED"."EMPLOYE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "JYHED"."EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNIR
--------------------------------------------------------

  ALTER TABLE "JYHED"."FOURNIR" MODIFY ("IDS" NOT NULL ENABLE);
  ALTER TABLE "JYHED"."FOURNIR" MODIFY ("IDP" NOT NULL ENABLE);
  ALTER TABLE "JYHED"."FOURNIR" ADD CONSTRAINT "FOURNIR_PK" PRIMARY KEY ("IDS", "IDP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARTENAIRE
--------------------------------------------------------

  ALTER TABLE "JYHED"."PARTENAIRE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "JYHED"."PARTENAIRE" ADD CONSTRAINT "PARTENAIRE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JYHED"."PARTENAIRE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "JYHED"."PARTENAIRE" MODIFY ("NUMTEL" NOT NULL ENABLE);
  ALTER TABLE "JYHED"."PARTENAIRE" MODIFY ("DATE_CONVENTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STOCK
--------------------------------------------------------

  ALTER TABLE "JYHED"."STOCK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "JYHED"."STOCK" ADD CONSTRAINT "STOCK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JYHED"."STOCK" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "JYHED"."STOCK" MODIFY ("QUANTITE" NOT NULL ENABLE);
  ALTER TABLE "JYHED"."STOCK" MODIFY ("TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FOURNIR
--------------------------------------------------------

  ALTER TABLE "JYHED"."FOURNIR" ADD CONSTRAINT "FOURNIR_FK1" FOREIGN KEY ("IDS")
	  REFERENCES "JYHED"."STOCK" ("ID") ENABLE;
  ALTER TABLE "JYHED"."FOURNIR" ADD CONSTRAINT "FOURNIR_FK2" FOREIGN KEY ("IDP")
	  REFERENCES "JYHED"."PARTENAIRE" ("ID") ENABLE;
